// Generated by gencpp from file robot_messages/LandmarkDistance.msg
// DO NOT EDIT!


#ifndef ROBOT_MESSAGES_MESSAGE_LANDMARKDISTANCE_H
#define ROBOT_MESSAGES_MESSAGE_LANDMARKDISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_messages
{
template <class ContainerAllocator>
struct LandmarkDistance_
{
  typedef LandmarkDistance_<ContainerAllocator> Type;

  LandmarkDistance_()
    : name()
    , distance(0.0)
    , z_orientation(0.0)  {
    }
  LandmarkDistance_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , distance(0.0)
    , z_orientation(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef double _distance_type;
  _distance_type distance;

   typedef double _z_orientation_type;
  _z_orientation_type z_orientation;




  typedef boost::shared_ptr< ::robot_messages::LandmarkDistance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_messages::LandmarkDistance_<ContainerAllocator> const> ConstPtr;

}; // struct LandmarkDistance_

typedef ::robot_messages::LandmarkDistance_<std::allocator<void> > LandmarkDistance;

typedef boost::shared_ptr< ::robot_messages::LandmarkDistance > LandmarkDistancePtr;
typedef boost::shared_ptr< ::robot_messages::LandmarkDistance const> LandmarkDistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_messages::LandmarkDistance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_messages::LandmarkDistance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'robot_messages': ['/home/user/Documents/ros-turtlebot-docking/src/robot_messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_messages::LandmarkDistance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_messages::LandmarkDistance_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_messages::LandmarkDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_messages::LandmarkDistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_messages::LandmarkDistance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_messages::LandmarkDistance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_messages::LandmarkDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "435047e3d21c4581dc109651649042ee";
  }

  static const char* value(const ::robot_messages::LandmarkDistance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x435047e3d21c4581ULL;
  static const uint64_t static_value2 = 0xdc109651649042eeULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_messages::LandmarkDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_messages/LandmarkDistance";
  }

  static const char* value(const ::robot_messages::LandmarkDistance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_messages::LandmarkDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name 	# Name of the simulated docking station landmark\n\
float64 distance 	# Distance to the landmark, in meters\n\
float64 z_orientation	# Orientation of the robot, in radians\n\
";
  }

  static const char* value(const ::robot_messages::LandmarkDistance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_messages::LandmarkDistance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.distance);
      stream.next(m.z_orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LandmarkDistance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_messages::LandmarkDistance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_messages::LandmarkDistance_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "z_orientation: ";
    Printer<double>::stream(s, indent + "  ", v.z_orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGES_MESSAGE_LANDMARKDISTANCE_H
